spring:
  application:
    name: spring-llm

  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: admin
    password: password

  ai:
    openai:
      api-key: empty
      chat:
        base-url: http://localhost:11434
        options:
#          model: deepseek-r1:1.5b
          model: gemma3
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
        base-url: http://localhost:11434
        enabled: true
    ollama:
      embedding:
        options:
          model: gemma3
      base-url: http://localhost:11434

  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 768

  docker:
    compose:
      lifecycle-management: start_only