spring:
  application:
    name: spring-llm

  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: admin
    password: password

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3
#        model: qwen3:1.7b
      embedding:
        enabled: true
        options:
          model: nomic-embed-text

  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 768

  docker:
    compose:
      lifecycle-management: start_only

weather:
  api-key: ${WEATHER_API_KEY}
  api-url: http://api.weatherapi.com/v1/current.json