spring:
  application:
    name: spring-llm

  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: admin
    password: password

  ai:
    openai:
      api-key: api_key
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3
      embedding:
        enabled: true
        options:
          model: nomic-embed-text

  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 768

  docker:
    compose:
      lifecycle-management: start_only